### ISSUE TITLE
Issue in Folder Creation

### ISSUE THREAD

**Issue by abilvj2** [nelson123-lab/Automation-at-Workplace#2]
The destination folder created by the automation run will ideally create a named folder, But when already a folder exists in the same name, it won't be created.  So rather to let this issue out, I would suggest a common nomenclature in Automation bots by adding timestamps to folder created with name. This has the advantage of finding the modified history along.

A string appending like utcNow() with your defined format for date-time can be added to the name of the folder created .

**Comment by nelson123-lab** [comment]
Ok thanks for informing the issue. I think it should be checked before creating the folder with name.
